apiVersion: apps/v1
kind: Deployment
metadata:
  name: one8pulse-userservice
  namespace: one8pulse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: one8pulse

  template:
    metadata:
      labels:
        app: one8pulse
        component: userservice
    spec:
      containers:
        - name: one8pulse-userservice
          image: 797111435256.dkr.ecr.us-east-1.amazonaws.com/backend/userservice:12
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://one8pulse-configserver-service.one8pulse.svc.cluster.local:8888"
          envFrom:
            - secretRef:
                name: one8pulse-secrets
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: one8pulse-user-service
  namespace: one8pulse
spec:
  selector:
    app: one8pulse
    component: userservice
  ports:
  - port: 80
    targetPort: 8081
  type: ClusterIP