apiVersion: apps/v1
kind: Deployment
metadata:
  name: one8pulse-userservice
  namespace: one8pulse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: one8pulse
  template:
    metadata:
      labels:
        app: one8pulse
        component: userservice
      containers:
      - name: one8pulse-userservice
        image: 797111435256.dkr.ecr.us-east-1.amazonaws.com/backend/userservice:12
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_CONFIG_IMPORT
            value: "optional:configserver:http://one8pulse-configserver-service.one8pulse.svc.cluster.local:8888"
        envFrom:
          - secretRef:
              name: one8pulse-secrets
        resources:
          requests:
            cpu: 200m
            memory: 384Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: one8pulse-user-service
  namespace: one8pulse
spec:
  selector:
    app: one8pulse
    component: userservice
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP