apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: one8pulse-gateway-destinationrule
  namespace: one8pulse
spec:
  host: one8pulse-gateway
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutiveErrors: 3
      interval: 30s
      baseEjectionTime: 30s
