spring:
  application:
    name: ai-service
  config:
    import: optional:configserver:http://one8pulse-configserver-service.one8pulse.svc.cluster.local:8888

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true