apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: one8pulse-secrets
  namespace: one8pulse
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "stage/one8pulse"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DB_HOST"
            objectAlias: "DB_HOST"
          - path: "DB_PASSWORD"
            objectAlias: "DB_PASSWORD"
          - path: "JWT_SECRET"
            objectAlias: "JWT_SECRET"
          - path: "SMTP_PASSWORD"
            objectAlias: "EMAIL_PASS"
          - path: "GEMINI_KEY"
            objectAlias: "GEMINI_KEY"
          - path: "MONGO_URL"
            objectAlias: "MONGO_URL"
  secretObjects:
  - secretName: one8pulse-secrets
    type: Opaque
    data:
    - key: DB_HOST
      objectName: DB_HOST
    - key: DB_PASSWORD
      objectName: DB_PASSWORD
    - key: JWT_SECRET
      objectName: JWT_SECRET
    - key: SMTP_PASSWORD
      objectName: SMTP_PASSWORD
    - key: GEMINI_KEY
      objectName: GEMINI_KEY
    - key: MONGO_URL
      objectName: MONGO_URL