spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: fitnessactivity
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

jwt:
  secret:
    key: ${JWT_KEY}
  expiration:
    ms: 86400000