server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL}
    username: postgres
    password: 952004

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    devtools:
      restart:
        enabled: false

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: afb403001@smtp-brevo.com
    password: ${SMTP_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          from: xespilon@gmail.com

jwt:
  secret:
    key: ${JWT_KEY}
  expiration:
    ms: 86400000
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
