apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-alb
  namespace: istio-system
  annotations:
    alb.ingress.kubernetes.io/group.name: one8pulse-internet-ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:797111435256:certificate/d83e36ad-c6b5-43da-aefe-844cf88a67de
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
spec:
  ingressClassName: alb
  rules:
  - host: prometheus.one8pulse.devcloudzone.store
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: istio-ingressgateway
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus
  namespace: istio-system

spec:
  hosts:
    - prometheus.one8pulse.devcloudzone.store

  gateways:
    - public-gateway

  http:
  - route:
      - destination:
          host: prometheus
          port:
            number: 9090